"""
FastTok type stubs — for IDE autocomplete and type checkers (mypy, pyright).
"""
from typing import List, Optional

class Compressor:
    def compress(self, text: str) -> str: ...
    def decompress(self, text: str) -> str: ...

class Tokenizer:
    model_name: str

    @staticmethod
    def from_pretrained(model_name: str, vocab: Optional[str] = None) -> "Tokenizer": ...
    def encode(self, text: str) -> List[int]: ...
    def decode(self, ids: List[int]) -> str: ...
    def count(self, text: str, budget: Optional[int] = None) -> int: ...
    def compress(self, text: str) -> str: ...
    def decompress(self, text: str) -> str: ...
    def smart_trim(self, text: str, max_tokens: int) -> str: ...
    def __repr__(self) -> str: ...
